export const DiaryList = 
[
    {
      "postId": 1,
      "title": "누군가의 일기장",
      "content": "오늘은 개발을 시작했따",
      "thumbnailImgURL": "",
      "likeCount": 3,
      "commentCount": 1,
      "viewCount": 12,
      "user": {
          "userId": 2019102240,
          "profileImgURL": "",
          "name": "한우준",
      },
      "createdDate": "2023/07/20",
      "isAnonymous": false,
      "isMyPost": true,
      "isLiked": false,
      "isBookmarked": false
  },
  {
    "postId": 2,
    "title": "누군가의 일기장",
    "thumbnailImgURL": "",
    "likeCount": 3,
    "commentCount": 1,
    "viewCount": 12,
    "user": {
        "userId": 2019102240,
        "profileImgURL": "",
        "name": "한우준",
    },
    "createdDate": "2023/07/20",
    "isAnonymous": false,
    "isMyPost": true,
    "isLiked": false,
    "isBookmarked": false
},    {
  "postId": 3,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 4,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 5,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 6,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 7,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 8,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},    {
  "postId": 9,
  "title": "누군가의 일기장",
  "thumbnailImgURL": "",
  "likeCount": 3,
  "commentCount": 1,
  "viewCount": 12,
  "user": {
      "userId": 2019102240,
      "profileImgURL": "",
      "name": "한우준",
  },
  "createdDate": "2023/07/20",
  "isAnonymous": false,
  "isMyPost": true,
  "isLiked": false,
  "isBookmarked": false
},
]